## EXERCISES

### Vector Multiplication
1. Produce 2 vectors, one with integers in the range [5,10] and the other [15,20] using the np.arange function
1. Without using any functions from the numpy module
    1. Compute the outer product of those vectors 
    1. Compute the "trace" of the resulting matrix
    
    ![trace](https://wikimedia.org/api/rest_v1/media/math/render/svg/3e5b6e82272fc5eeca6d510388e0a2bd0a6c6463)
    
    
Complete the same items using numpy operations

In [9]:
import numpy as np

a = np.arange(5,11)
b = np.arange(15,21)


# without numpy
# outer product
outer_product = []

for i in range (len(a)):
    row = []
    for j in range(len(b)):
        row.append(a[i]*b[j])
    
    outer_product.append(row)
    
print("outer product: ", outer_product)


# trace
trace_list = []
for i in range (len(outer_product)):
    trace_value = outer_product[i][i]
    trace_list.append(trace_value)

print('trace:', sum(trace_list))


# With numpy
# outer product
print('outer product: ', np.outer(a,b))

# trace
print('trace: ', np.trace(np.outer(a,b)))

outer product:  [[75, 80, 85, 90, 95, 100], [90, 96, 102, 108, 114, 120], [105, 112, 119, 126, 133, 140], [120, 128, 136, 144, 152, 160], [135, 144, 153, 162, 171, 180], [150, 160, 170, 180, 190, 200]]
trace: 805
outer product:  [[ 75  80  85  90  95 100]
 [ 90  96 102 108 114 120]
 [105 112 119 126 133 140]
 [120 128 136 144 152 160]
 [135 144 153 162 171 180]
 [150 160 170 180 190 200]]
trace:  805


### Matrix Multiplication
* Two matricies can be multiplied if their inner dimensions match (eg. 2x3 * 3x5 -> 2x5). The best rule for working with and mutliplying matricies is to remember (rows x columns). This applies to both the dimensions of a matrix (a 2x3 matrix has 2 rows and 3 columns) as well as multiplication (you multiply the rows of the first matrix by the columns of the second). 

* When multiplying two matricies of dimension (M x N)*(N x P) the resulting matrix is (M x P). The upper element of the reslting matrix is the inner (or dot) product of the first row of the first matrix and the first column of the second matrix

![two matrices](https://wikimedia.org/api/rest_v1/media/math/render/svg/16b1644351bc2041175b19cbc65da03ef78130c7)

![store product in matrix C](https://wikimedia.org/api/rest_v1/media/math/render/svg/00ac0c831c365b7424cc43239aae8cebea27c56c)

![matrix multiply](https://wikimedia.org/api/rest_v1/media/math/render/svg/3cfeccef1c8c7e6da0ddf08daed8dbf3c6f50c5e)

for i = 1, ..., n and j = 1, ..., p.

1. Make two matrices of random numbers (A and B). A should be a 4x3 matrix and B should be a 3x4 matrix. Multiply A by B using (to a resulting matrix C) using:
    1. a conventional for-loop
    1. list comprehension
    1. numpy operator
    
2. After you have C, pull out the upper quadrant using fancy indexing, and then replace the main diagonal (upper left to lower right) with 0s. 

In [55]:
A = np.random.random(size=(4,3))
B = np.random.random(size=(3,4))
print(A)
print(B)

# for loop
out = np.zeros((4,4))

for i in range(len(A)):    
    for j in range(len(B[0])):        
        for k in range(len(B)):
            out[i][j] += A[i][k] * B[k][j]    
print('out: ', out)

# list comprehension
out2 = [[sum(a*b for a,b in zip(A_row,B_col)) for B_col in zip(*B)] for A_row in A]
print('out2: ', out2)

# with numpy
out3 = np.matmul(A,B)
print('out3: ', out3)



# pull out upper quadrant
quad = out3[:2,2:]
print ('Upper quadrant: ', quad)

# fill diagonals
np.fill_diagonal(out3, 0)
out3

[[0.97857505 0.89811024 0.97384208]
 [0.5714586  0.66029931 0.31085512]
 [0.82074155 0.73928828 0.71221291]
 [0.65766323 0.76708666 0.67989357]]
[[0.007548   0.2135029  0.7298444  0.64991681]
 [0.55668418 0.8071534  0.77907253 0.02604122]
 [0.81543425 0.49743427 0.45932951 0.76082151]]
out:  [[1.30145423 1.41826376 1.86121493 1.40030026]
 [0.62537346 0.80960089 1.07428184 0.62510081]
 [0.99850785 1.12622886 1.50211322 1.0945326 ]
 [0.98639756 1.09777198 1.38990315 0.96467992]]
out2:  [[1.3014542320501714, 1.4182637636455182, 1.8612149347251488, 1.4003002621543854], [0.6253734590950494, 0.8096008874281397, 1.07428183803502, 0.6251008087439822], [0.9985078508624274, 1.12622885656956, 1.5021132174813172, 1.094532604408081], [0.9863975583450085, 1.0977719768656844, 1.3899031533576798, 0.9646799178371737]]
out3:  [[1.30145423 1.41826376 1.86121493 1.40030026]
 [0.62537346 0.80960089 1.07428184 0.62510081]
 [0.99850785 1.12622886 1.50211322 1.0945326 ]
 [0.98639756 1.09777198 1.38990315 0.96

array([[0.        , 1.41826376, 1.86121493, 1.40030026],
       [0.62537346, 0.        , 1.07428184, 0.62510081],
       [0.99850785, 1.12622886, 0.        , 1.0945326 ],
       [0.98639756, 1.09777198, 1.38990315, 0.        ]])